-- MySQL Script generated by MySQL Workbench
-- Mon Sep  4 22:25:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema StaffManager
-- -----------------------------------------------------
-- 职工工资在线管理信息

-- -----------------------------------------------------
-- Schema StaffManager
--
-- 职工工资在线管理信息
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `StaffManager` DEFAULT CHARACTER SET utf8 ;
USE `StaffManager` ;

-- -----------------------------------------------------
-- Table `StaffManager`.`staff_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StaffManager`.`staff_info` (
  `id` INT NOT NULL DEFAULT 0 COMMENT 'ID',
  `snum` INT(10) NOT NULL DEFAULT 0 COMMENT '职工号',
  `sname` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '姓名',
  `ssex` CHAR(4) NULL DEFAULT 0 COMMENT '性别 0为男 女为1',
  `sbir` DATETIME(20) NULL DEFAULT 0 COMMENT '生日',
  `gnum` INT(10) NOT NULL DEFAULT 0 COMMENT '岗位编号',
  `stime` INT NULL COMMENT '工作年限',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sid_UNIQUE` (`id` ASC),
  UNIQUE INDEX `snum_UNIQUE` (`snum` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `StaffManager`.`gang_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StaffManager`.`gang_info` (
  `id` INT NOT NULL DEFAULT 0 COMMENT 'ID',
  `gname` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '岗位名称',
  `gbasemon` FLOAT NULL DEFAULT 0 COMMENT '基本工资',
  `gjinmon` FLOAT NULL DEFAULT 0,
  `gtemon` FLOAT NULL DEFAULT 0 COMMENT '特殊津贴',
  `gnum` INT(10) NULL DEFAULT 0 COMMENT '岗位编号',
  `staff_info_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gid_UNIQUE` (`id` ASC),
  UNIQUE INDEX `gname_UNIQUE` (`gname` ASC),
  INDEX `fk_gang_info_staff_info_idx` (`staff_info_id` ASC))
ENGINE = MyISAM
COMMENT = '岗位信息表';


-- -----------------------------------------------------
-- Table `StaffManager`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StaffManager`.`message` (
  `id` INT NOT NULL DEFAULT 0 COMMENT '信息id',
  `mtitle` VARCHAR(100) NULL DEFAULT '' COMMENT '留言内容',
  `mcontent` VARCHAR(445) NULL DEFAULT '' COMMENT '留言内容',
  `mtime` DATETIME(20) NULL DEFAULT '' COMMENT '留言时间',
  `mwho` VARCHAR(45) NULL DEFAULT '' COMMENT '留言人',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mid_UNIQUE` (`id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `StaffManager`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StaffManager`.`manager` (
  `id` INT NOT NULL DEFAULT 0 COMMENT 'id',
  `mname` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '管理员姓名',
  `mphone` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '联系电话',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mid_UNIQUE` (`id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `StaffManager`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StaffManager`.`login` (
  `id` INT NOT NULL DEFAULT 0 COMMENT 'id\n',
  `sname` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '登录名',
  `pwd` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '登录密码',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `lid_UNIQUE` (`id` ASC),
  UNIQUE INDEX `lname_UNIQUE` (`lname` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `StaffManager`.`staff_info_has_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StaffManager`.`staff_info_has_message` (
  `staff_info_id` INT NOT NULL,
  `message_id` INT NOT NULL,
  PRIMARY KEY (`staff_info_id`, `message_id`),
  INDEX `fk_staff_info_has_message_message1_idx` (`message_id` ASC),
  INDEX `fk_staff_info_has_message_staff_info1_idx` (`staff_info_id` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
